# Generated by Django 5.2.8 on 2025-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_documentocalificaciones_pensum_planificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='anio',
            field=models.IntegerField(default=2025),
        ),
    ]
