# Generated by Django 5.2.8 on 2025-12-08 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_asignatura_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='tutores',
            field=models.ManyToManyField(blank=True, related_name='tutorias_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
