# Generated by Django 5.2.9 on 2025-12-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_docente_tipo_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinscripcion',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_inscritos', to='gestion.seccion'),
        ),
    ]
